### PR TITLE
Added a design of launch page

### PR DESCRIPTION
**Pull request by EANimesha**
I am not an expert designer. This is just an idea. Check if you like
logo_design

### CODE REVIEW

**Comment by AlinaStepanova** [comment]
Hi, @EANimesha thanks for your time and attempt! As I mentioned in the comment earlier: https://github.com/AlinaStepanova/Lyrics/issues/1#issuecomment-706513722, only the launcher icon is needed

**Comment by EANimesha** [comment]
How about this?
logo

**Comment by AlinaStepanova** [comment]
Hi @EANimesha the icon looks good, please update your pull request

**Comment by EANimesha** [comment]
> Hi @EANimesha the icon looks good, please update your pull request
@AlinaStepanova done

**Review by AlinaStepanova — APPROVED** [review]

**Pull request merged**
